# SuperManUS Redis Deployment
# Component: Data Storage
# Module: Redis Cache & Session Store  
# Dependencies: None (base infrastructure)
# Last Modified: 2025-09-03
# Session: Current
# Purpose: Redis deployment for caching, session management, and Celery broker

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: supermanus
  labels:
    app: redis
    component: database
    tier: infrastructure
spec:
  replicas: 1
  strategy:
    type: Recreate  # Redis needs persistent storage
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        component: database
        tier: infrastructure
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - --appendonly
        - "yes"
        - --maxmemory
        - "1gb"
        - --maxmemory-policy
        - "allkeys-lru"
        - --bind
        - "0.0.0.0"
        - --protected-mode
        - "no"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi" 
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: REDIS_PORT
          value: "6379"
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
      restartPolicy: Always

---
# Redis Service for internal cluster access
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: supermanus
  labels:
    app: redis
    component: database
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP

---
# PersistentVolumeClaim for Redis data persistence
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: supermanus
  labels:
    app: redis
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""  # Use default storage class

---
# ConfigMap for Redis configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: supermanus
  labels:
    app: redis
    component: configuration
data:
  redis.conf: |
    # SuperManUS Redis Configuration
    # Optimized for Celery broker and caching
    
    # Memory settings
    maxmemory 1gb
    maxmemory-policy allkeys-lru
    
    # Persistence settings
    appendonly yes
    appendfsync everysec
    
    # Network settings
    bind 0.0.0.0
    protected-mode no
    port 6379
    
    # Performance settings
    tcp-keepalive 60
    timeout 300
    
    # Logging
    loglevel notice
    
    # Client settings  
    tcp-backlog 511
    databases 16